### ISSUE TITLE
Code snippets for flutter

### ISSUE THREAD

**Issue by mehulagg** [demianborba/spectrum-dsp#5]
I am not able to get and use code snippets for flutter .

**Comment by demianborba** [comment]
Hello @mehulagg, thank you for filing the issue.
Adobe Spectrum doesn't support Flutter as a platform yet, that is why you don't see snippets for components for it.
But you can compile design tokens into Flutter (Dart) tokens with the extension, and then developers can use them to feed their Flutter apps. Hope it helps.
