### ISSUE TITLE
Curious about the workflow to add custom tokens

### ISSUE THREAD

**Issue by johnjacobkenny** [demianborba/spectrum-dsp#6]
Hi @demianborba thanks for the awesome work being done in this space. I am excited to be working as a developer in these times. :partying_face: 

I have a question about the workflow of creating the DSP. I have been able to create my DSP using the VS Code plugin. From my design team, I have received the link for the library, and I am able to generate the DSP from VS Code. However I am not able to get custom tokens in the DSP from that library link. The designer mentioned that from XD there is no way to include custom tokens. So I am curious about how you added the custom tokens, whether manually through the VS Code plugin, or through some other automated pipeline.

Thanks :heart:

**Comment by demianborba** [comment]
Great question @johnjacobkenny, and thanks for the kind words. Your team is correct, XD doesn't support custom tokens yet, but DSP does. So what we did for Spectrum was adding them outside of XD, for custom tokens, and also aliases.
