### ISSUE TITLE
support for light/dark mode?

### ISSUE THREAD

**Issue by daKmoR** [demianborba/spectrum-dsp#7]
how would that work? 🤔

**Comment by demianborba** [comment]
Hi @daKmoR . The extension doesn't support themes or platforms yet, but you can use different naming conventions to achieve your goal. Example: You can name a token or alias as spectrum.ios.dark.background-button. Would that work for you?

**Comment by daKmoR** [comment]
Unfortunately, that will not be good enough for us 😅  and on top of that we have even more specific needs 😅
so we now went with a custom layer on top of Style Dictionary...

I'm still gonna keep up to date regarding dsp - looking forward to where it leads 🤗

**Comment by Flammae** [comment]
[react spectrum](https://react-spectrum.adobe.com/react-spectrum/index.html) has light/dark modes. how did you implement it?
